FROM jenkins/jenkins:lts

USER root

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    curl \
    unzip \
    python3 \
    python3-pip \
    docker.io && \
    pip3 install awscli && \
    apt-get clean

USER jenkins
